apiVersion: v1
kind: Namespace
metadata:
  name: demo-quarkus-petclinic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-petclinic
  labels:
    app: quarkus-petclinic
  namespace: demo-quarkus-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-petclinic
  template:
    metadata:
      labels:
        app: quarkus-petclinic
    spec:
      containers:
        - name: quarkus-petclinic
          image: quay.io/dszegedi/quarkus-petclinic:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-petclinic-service
  namespace: demo-quarkus-petclinic
spec:
  selector:
    app: quarkus-petclinic
  ports:
  - name: quarkus-petclinic-port
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quarkus-petclinic-route
  namespace: demo-quarkus-petclinic
spec:
  to:
    kind: Service
    name: quarkus-petclinic-service
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
---
