apiVersion: v1
kind: Namespace
metadata: 
  name: load-cpu

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random
  namespace: load-cpu
spec:
  selector:
    matchLabels:
      app: random
  replicas: 2
  template:
    metadata:
      labels:
        app: random
    spec:
      containers:
        - name: hamster
          image: registry.access.redhat.com/ubi9-micro:latest
          resources:
            requests:
              cpu: 1
              memory: 500Mi
          command: ["/bin/sh"]
          args:
            - "-c"
            - "cat /dev/random > dev/null"
