apiVersion: v1
kind: Namespace
metadata:
  name: load-gpu

---

apiVersion: v1
kind: Pod
metadata:
  name: gpu-operator-test
  namespace: load-gpu
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-vector-add
    image: "nvcr.io/nvidia/k8s/cuda-sample:nbody"
    args:
    - -benchmark 
    - -numbodies=512000"
    resources:
      limits:
         nvidia.com/gpu: 1
